spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://testDB:3306/TEST_TABLE?createDatabaseIfNotExist=true
    # {testDB:3306} ? ??? ?? ????? ??? ??
    # TEST_TABLE?createDatabaseIfNotExist=true TEST_TABLE??? ???? ??? ?? ???? ??
    username: root #root id
    password: qwer1234 # DB ????

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false