spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://testDB:3306/TEST_TABLE?createDatabaseIfNotExist=true
    username: root
    password: qwer1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false